name: Work 1 Dorx

on:
  push:
    branches:
      - test_1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Impresión 1
        run: echo "Impresión 1"
        
      - name: Impresión 2
        run: echo "Impresión 2"

      - name: Impresión 3
        run: echo "Impresión 3"
